# Gunakan image dasar Airflow
FROM apache/airflow:2.4.3

# Install scikit-learn dan mlflow
RUN pip install --no-cache-dir scikit-learn mlflow google-cloud-bigquery google-auth ipaddress

# EXPOSE 5001